name: WizardXP
main: fr.iwebster.wizardxp.WizardXP
version: 1.0.3
permissions:
    wizardxp.*:
        description: Gives access to create as much potion as needed, plus the scrawl of help
        children:
            wizardxp.single: true
            wizardxp.stack: true
            wizardxp.fill: true
            wizardxp.help: true
    wizardxp.single:
        description: Allows to create one bottle with a stick
        default: not op
    wizardxp.stack:
        description: Allows to create a stack of bottles with a redstone torch
        default: not op
    wizardxp.fill:
        description: Allows to create as much bottles as possible
        default: not op
    wizardxp.help:
        description: Tells the sender about the usage of the plugin.
        default: not op
commands:
   wizardxp:
      description: Tells the sender about the usage of the plugin.
      usage: /wizardxp <page>
      permission: wizardxp.help
      permission-message: Only wizards can read the scrawl of XP conveying !
